# Generated by Django 3.2.3 on 2021-06-29 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='No category', max_length=25, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='user',
            name='raiting',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Raiting'),
        ),
    ]
