# Generated by Django 3.2.3 on 2021-06-30 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210629_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/users/', verbose_name='User image'),
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(100)], verbose_name='Description'),
        ),
    ]
