# Generated by Django 3.2.3 on 2021-06-30 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210630_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(max_length=250, validators=[django.core.validators.MinLengthValidator(100)], verbose_name='Description'),
        ),
    ]
